cmake_minimum_required(VERSION 3.24)
project(cuda_ch23_denoising LANGUAGES CXX CUDA)
set(CMAKE_CUDA_STANDARD 17)
set(CMAKE_CUDA_STANDARD_REQUIRED ON)
add_executable(denoising denoising.cu)
target_include_directories(denoising PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/../../common)
target_compile_options(denoising PRIVATE $<$<COMPILE_LANGUAGE:CUDA>:-lineinfo>)
enable_testing()
add_test(NAME ch23_denoising COMMAND denoising ${CMAKE_CURRENT_BINARY_DIR}/ch23-images)
