cmake_minimum_required(VERSION 3.24)
project(cuda_ch22_mean_gaussian LANGUAGES CXX CUDA)
set(CMAKE_CUDA_STANDARD 17)
set(CMAKE_CUDA_STANDARD_REQUIRED ON)
add_executable(mean_gaussian mean_gaussian.cu)
target_include_directories(mean_gaussian PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/../../common)
target_compile_options(mean_gaussian PRIVATE $<$<COMPILE_LANGUAGE:CUDA>:-lineinfo>)
enable_testing()
add_test(NAME ch22_mean_gaussian COMMAND mean_gaussian ${CMAKE_CURRENT_BINARY_DIR}/ch22-images)
