cmake_minimum_required(VERSION 3.24)
project(cuda_ch6 LANGUAGES CXX CUDA)
set(CMAKE_CUDA_STANDARD 17)
set(CMAKE_CUDA_STANDARD_REQUIRED ON)
add_executable(resampling resampling.cu)
target_compile_options(resampling PRIVATE $<$<COMPILE_LANGUAGE:CUDA>:-lineinfo>)
enable_testing()
add_test(NAME ch6_resampling COMMAND resampling ${CMAKE_CURRENT_BINARY_DIR}/images)
