cmake_minimum_required(VERSION 3.24)
project(cuda_ch24_image_resampling LANGUAGES CXX CUDA)
set(CMAKE_CUDA_STANDARD 17)
set(CMAKE_CUDA_STANDARD_REQUIRED ON)
add_executable(image_resampling image_resampling.cu)
target_include_directories(image_resampling PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/../../common)
target_compile_options(image_resampling PRIVATE $<$<COMPILE_LANGUAGE:CUDA>:-lineinfo>)
enable_testing()
add_test(NAME ch24_image_resampling COMMAND image_resampling ${CMAKE_CURRENT_BINARY_DIR}/ch24-images)
