cmake_minimum_required(VERSION 3.24)
project(cuda_ch8 LANGUAGES CXX CUDA)
set(CMAKE_CUDA_STANDARD 17)
set(CMAKE_CUDA_STANDARD_REQUIRED ON)
add_executable(operators operators.cu)
target_compile_options(operators PRIVATE $<$<COMPILE_LANGUAGE:CUDA>:-lineinfo>)
enable_testing()
add_test(NAME ch8_operators COMMAND operators)
